version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/daily-quote-api
  build:
    env:
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - go build -a -installsuffix cgo ./cmd/daily-quote-api
