openapi: 3.1.0
info:
  version: 0.0.2
  title: Daily quotes API
  description: Provides quotes
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
paths:
  /quote:
    get:
      summary: Responds with a quote
      tags:
        - Quotes
      parameters:
        - $ref: '#/components/parameters/OfThe'
      responses:
        200:
          description: Fetched quote successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        400:
          $ref: '#/components/responses/ValidationError'
        500:
          $ref: '#/components/responses/InternalError'

components:
  parameters:
    OfThe:
      in: query
      name: of-the
      description: The time interval the quite is refreshed
      schema:
        type: string
        default: day
        enum:
          - second
          - minute
          - hour
          - day
          - week
          - fortnight
          - month
          - year
  schemas:
    Quote:
      type: object
      description: Quote object
      properties:
        title:
          type: string
          default: Quote of the day
          enum:
            - Quote of the second
            - Quote of the minute
            - Quote of the hour
            - Quote of the day
            - Quote of the week
            - Quote of the fortnight
            - Quote of the month
            - Quote of the year
        quote:
          type: string
          description: The quote itself
          examples:
            - The best way out is always through.
        author:
          type: string
          description: The author of the quote
          examples:
            - Robert Frost
  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                examples:
                  - Some invalid value input
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                examples:
                  - Unexpected error occurred
